spring:
    datasource:
      url: ${POSTGRES_URL}
      username: ${POSTGRES_USERNAME}
      password: ${POSTGRES_PASS}

info:
  name: "account-service"
  description: "Service quản lý tài khoản cho Bookshop"
  version: "1.0.0"