server:
  port: 0

spring:
  mail:
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}  
    # host: "smtp.gmail.com"
    # port: 587
    # properties:
    #   mail:
    #     smtp:
    #       auth: true
    #       starttls:
    #         enable: true
    #       ssl:
    #         protocols: "TLSv1.2"