spring:
  datasource:
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: ${DB_URL}
  jpa:
    show-sql: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.BytesSerializer
      # value-serializer: com.example.bookshop.orderservice.event.OrderPlacementValueSerializer
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false

payment:
  stripe:
    secret-key: ${STRIPE_SECRET_KEY}
